import { Logger } from '@nestjs/common';
import { ErrorManager } from '../exceptions/error-manager';
import { PerformOperationParams } from '../interfaces/operation-handler.interface';

/**
 * Clase abstracta: BaseService
 *
 * üõ†Ô∏è Clase base para todos los servicios y casos de uso en la capa de aplicaci√≥n.
 * Proporciona un wrapper est√°ndar para ejecutar l√≥gica de negocio con:
 * - Logging estructurado
 * - Contexto din√°mico
 * - Manejo centralizado de errores
 *
 * üöÄ Al extender esta clase, cada servicio gana trazabilidad y robustez
 * sin tener que repetir l√≥gica de logging o try/catch.
 */

export abstract class BaseService {
  protected readonly logger: Logger;
  constructor(contextName: string) {
    this.logger = new Logger(contextName);
  }

  /**
   * Ejecuta una operaci√≥n controlada dentro de un servicio o use case.
   *
   * üîÅ Encapsula cualquier funci√≥n as√≠ncrona con logs de inicio, √©xito y fallo.
   * Si ocurre un error, lo maneja de forma centralizada usando `ErrorManager`.
   *
   * @template T - Tipo del resultado esperado.
   * @param operation - Funci√≥n que contiene la l√≥gica del servicio.
   * @param context - Nombre del contexto (por defecto: 'SERVICE').
   * @param functionName - Nombre espec√≠fico de la operaci√≥n, √∫til para logs.
   * @returns El resultado de la operaci√≥n si tiene √©xito.
   * @throws Una excepci√≥n manejada o relanzada por `ErrorManager`.
   *
   * @example
   * return this.performServiceOperation({
   *   functionName: 'listar empresas',
   *   context: 'listarEmpresasUseCase',
   *   operation: async () => this.empresaRepo.listarEmpresas()
   * });
   */
  protected async performServiceOperation<T>({
    operation,
    context = 'SERVICE',
    functionName,
  }: PerformOperationParams<T>): Promise<T> {
    try {
      this.logger.log(
        `üü¢ [${context}] ${functionName ?? 'Operaci√≥n'} iniciada`,
      );
      const result = await operation();
      this.logger.log(
        `‚úÖ [${context}] ${functionName ?? 'Operaci√≥n'} completada con √©xito`,
      );
      return result;
    } catch (error) {
      this.logger.error(
        `‚ùå [${context}] ${functionName ?? 'Operaci√≥n'} fallida`,
        error instanceof Error ? error.stack : String(error),
      );
      ErrorManager.handle(error);
    }
  }
}
